### ISSUE TITLE
csgo windows effects.temp_entities.physics_prop crashes server

### ISSUE THREAD

**Issue by high-voltage** [Source-Python-Dev-Team/Source.Python#105]
```
from players.entity import Player as PlayerEntity
from players.helpers import index_from_userid

from events import Event
from engines.server import engine_server
from filters.recipients import RecipientFilter

from effects import temp_entities
from mathlib import Vector, QAngle
from engines.precache import Model

@Event('player_say')
def player_say(event):
    userid = event.get_int('userid')
    index = index_from_userid(userid)
    player = PlayerEntity(index)
    model = engine_server.precache_model("models/weapons/w_bullet.mdl")
    temp_entities.physics_prop(RecipientFilter(), 0.0, model, 0, 
        player.eye_location + player.view_vector * 150, QAngle(0,0,0), Vector(0,0,0), 0, 0
    )
```

Edit: No error in console. Tested only on windows csgo, sp version 181.

**Comment by invincibleqc** [comment]
What if you use the TempEntity class?

```python
from effects.base import TempEntity

@Event('player_say')
def player_say(event):
    userid = event.get_int('userid')
    index = index_from_userid(userid)
    player = PlayerEntity(index)

    te = TempEntity('physicsprop')
    te.origin = player.eye_location + (player.view_vector * 150)
    te.model = Model('models/weapons/w_bullet.mdl')
    te.create()

```

**Comment by high-voltage** [comment]
Yes, that works thanks! Is there a way I can find out which attributes ```te``` provides?

**Comment by invincibleqc** [comment]
It crashes cause the SDK is outdated. If we look at the prototype of the compiled method, we can see that they added a color24 argument (m_clrRender):

 ```CTempEntsSystem::PhysicsProp(IRecipientFilter &, float, int, int, Vector const&, QAngle const&, Vector const&, int, int, color24)```

It would requires a fix directly into the SDK for CS:GO. Actually, it would requires a bunch of fixes for other effects (and/or games/engines) as well. For example, CEffectData structure differs on most engines, CTEPlayerAnimEvent too, etc.

To be honnest, rather than fixing the SDKs, I think we should totally remove the ITempEntsSystem class. It offers less effects, wrappers are outdated, and we cannot access all the parameters an effect has to offer in most cases, so yeah... I think we should remove it.

**Comment by satoon101** [comment]
> Is there a way I can find out which attributes te provides?

They are in the data, where you found them, but also you can use dir() on the `te` object, as we also added the dynamic attributes to be listed:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/effects/base.py#L310


> To be honnest, rather than fixing the SDKs, I think we should totally remove the ITempEntsSystem class.

As long as we aren't losing any functionality, I am good with that change.

**Comment by Ayuto** [comment]
``temp_entities`` is about to get removed. Use ``TempEntity`` instead.
