### ISSUE TITLE
CKnife doesn't have a rendermode?

### ISSUE THREAD

**Issue by backraw** [Source-Python-Dev-Team/Source.Python#112]
Hi, I'm trying to get the following working on player_spawn:

1. issue use weapon_knife on the client to ensure they're carrying a knife (works fine)
2. set the knife's color to WHITE with alpha 20 (generates the error)

Error:
```
[SP] Caught an Exception: 
Traceback (most recent call last): 
  File '../addons/source-python/packages/source-python/listeners/tick.py', line 54, in _tick 
    self.pop(0).execute() 
  File '../addons/source-python/packages/source-python/listeners/tick.py', line 115, in execute 
    return self.callback(*self.args, **self.kwargs) 
  File '../addons/source-python/packages/source-python/players/weapons/__init__.py', line 382, in set_weapon_color 
    Entity(index).color = color 
  File '../addons/source-python/packages/source-python/entities/entity.py', line 114, in __setattr__ 
    object.__setattr__(self, attr, value) 
  File '../addons/source-python/packages/source-python/entities/entity.py', line 341, in set_color 
    self.render_mode |= RenderMode.TRANS_COLOR 
  File '../addons/source-python/packages/source-python/entities/entity.py', line 126, in __setattr__ 
    setattr(server_class(self.pointer, wrap=True), attr, value) 
  File '../addons/source-python/packages/source-python/entities/classes.py', line 510, in fset 
    pointer), 'set_key_value_' + type_name)(name, value) 
 
NameError: 'rendermode' is not a valid KeyValue for entity class 'CKnife'. 
 
 
sp version
Current Source.Python version: 256
```

I assume the rendermode was forgotten for CKnife here. :D

**Comment by Ayuto** [comment]
Are you testing in CS:GO? This isn't an issue on our end. See also: issue #78

**Comment by satoon101** [comment]
As @Ayuto pointed out, this was already handled in issue #78.  For all weapon entities, you must use the weapons.entity.Weapon class if you wish to set the color.  We overwrite the set_color method of entities.entity.Entity there due to all the render keyvalues not existing for weapons:

https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/weapons/entity.py#L150

**Comment by backraw** [comment]
Ooooh, sorry.

**Comment by satoon101** [comment]
The same error will occur in all games if you use Entity instead of Weapon.  The further issue with CS:GO is that the color/alpha of the weapon the player is carrying cannot be changed.  If you change the color/alpha while a player is holding the weapon, it will still show with full color until they drop it.  Once it is dropped, it will show with the correct color/alpha it was changed to.

**Comment by backraw** [comment]
Will it work using Weapon?

**Comment by satoon101** [comment]
On every game except for CS:GO, yes.  There is no currently known way to accomplish this in CS:GO, afaik.

**Comment by backraw** [comment]
Okay thanks.
