### ISSUE TITLE
Prehook Saytext2 buffer.read_string decode error

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#186]
http://forums.sourcepython.com/viewtopic.php?p=9787#p9787

Example username could be: ┼ N‡GH†MΔƦΣ CRΣ3PƦ ⺠

**Comment by Ayuto** [comment]
This error is occurs, because the engine truncates the name and leaves a splitted multi-byte character at the end of the string.

Let's take a look at the bytes of the original name. It has 20 characters, but is actually 33 bytes long, because it contains multi-byte characters:
```
00 b'┼' [226, 148, 188]
01 b' ' [32]
02 b'N' [78]
03 b'‡' [226, 128, 161]
04 b'G' [71]
05 b'H' [72]
06 b'†' [226, 128, 160]
07 b'M' [77]
08 b'Δ' [206, 148]
09 b'Ʀ' [198, 166]
10 b'Σ' [206, 163]
11 b' ' [32]
12 b'C' [67]
13 b'R' [82]
14 b'Σ' [206, 163]
15 b'3' [51]
16 b'P' [80]
17 b'Ʀ' [198, 166]
18 b' ' [32]
19 b'⺠' [226, 186, 160]
```
Now, replace ``param1.read_string()`` with this code to see, which bytes are provided by the engine.
```python
    for i in range(35):
        print('{:02d}'.format(i), buffer_read.read_byte())
```
This results in the following, when typing ``abc`` in the chat.
```
00 226
01 148
02 188
03 32
04 78
05 226
06 128
07 161
08 71
09 72
10 226
11 128
12 160
13 77
14 206
15 148
16 198
17 166
18 206
19 163
20 32
21 67
22 82
23 206
24 163
25 51
26 80
27 198
28 166
29 32
30 226
31 0
32 97
33 98
34 99
```
As we can see the last two bytes of the last character are missing, because after the byte 226 the string is already terminated followed by the bytes 97, 98 and 99 (a, b and c). This means that the engine truncates the string and leaves a splitted multi-byte character at the end of the string, which can't be decoded.

We also experienced this behaviour in a few other cases (see issue #27). In these cases we have added a "fix" directly into the SP code, but in this case it doesn't make much sense to do so, because the error could tell you that you are really doing something wrong.

However, I have added a context manager that allows you to easily workaround that engine bug:
https://github.com/Source-Python-Dev-Team/Source.Python/commit/b8119393a3b9ccb64410c5ca5b3b482e84743270

To fix your issue, you can simply use this snippet:
```python
    with ignore_unicode_errors():
        param1 = buffer_read.read_string()
```
