### ISSUE TITLE
Latest CS:GO Update Broke Source.Python (Again)

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#199]
Hey,

Nothing else than: 

``
[Source.Python]` Loading...
[Source.Python] Failed to load the main module.
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
[Source.Python] Failed to unload the main module.
[Source.Python] Unloaded successfully.
``

Windows 10 - CS:GO

**Comment by satoon101** [comment]
Do you have bots that load on your server during server start?  SP loads fine for me, but then crashes when the first player joins, whether that be a human player or a bot.  This is without any SP plugins loaded and no other server plugins.  I have not had time to narrow it down, and I am not sure when I will have time to do so.

```
sp info

Date          : 2017-05-25 11:52:12.026386
OS            : Windows-10-10.0.14393
Game          : csgo
SP version    : unversioned
Server plugins:
   00: Source.Python, (C) 2012-2016, Source.Python Team.
SP plugins:
```

It's `unversioned` because I always build myself locally.  Everything is up-to-date, though.

**Comment by Frag1337** [comment]
Im only running bot_quota through server console.

**Comment by satoon101** [comment]
407d523 fixed this for me, and now players can join the server without it crashing.  Are you seeing the same thing, @Frag1337 ?

**Comment by Frag1337** [comment]
Latest Build fixed both of my issues. Thanks @satoon101
