### ISSUE TITLE
Log messages don't show their origin

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#211]
I never really noticed that before, but Source.Python's log messages aren't showing their origin.

Example log message:
```
2017-07-04 20:35:55 - sp	-	DEBUG	OnEntityDeleted.__init__<<function _on_entity_deleted at 0x1CD16228>>
```
It's sent by ``listeners_logger``, so the log message should actually say the following:
```
2017-07-04 20:35:55 - sp.listeners	-	DEBUG	OnEntityDeleted.__init__<<function _on_entity_deleted at 0x1CD16228>>
```

**Comment by invincibleqc** [comment]
This is because every `_LogInstance` internally log to the main [_sp_logger](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/loggers.py#L252-L256):
```python
        # Print to the main SP log file?
        if SP_LOG & areas:

            # Print to the SP log file
            _sp_logger.logger.log(level, msg, *args, **kwargs)
```
So while formatting the `name` is `sp` and not `sp.<parent>`. A lazy fix would be to simply overwrite/restore the logger's name:
```python
        # Print to the main SP log file?
        if SP_LOG & areas:

            # Save/Overwrite the logger's name
            name = _sp_logger.logger.name
            _sp_logger.logger.name = self.logger.name

            # Print to the SP log file
            _sp_logger.logger.log(level, msg)

            # Restore the name
            _sp_logger.logger.name = name
```
Otherwise it would requires duplicate code with a new formatter in order to handle that specific case.

**Comment by invincibleqc** [comment]
Pushed a [new branch](https://github.com/Source-Python-Dev-Team/Source.Python/commits/issue_211) with the suggested changes which fixes both Python and C++ sides. Also removes the PythonLog function that was accepting a "method name" because it was redundant.

**Comment by invincibleqc** [comment]
Looked more into the `logging` module and found a [better way by using the "extra" keyword](https://github.com/Source-Python-Dev-Team/Source.Python/commit/b69a4919774bcff7471e85d4f3305ee97aff3364)!

**Comment by Ayuto** [comment]
Yes, that looks better!

>As a side note, I think we should remove the %Y-%m-%d from the time format, it is redundant since we create a single file per day and we include that info in the file name...

Agreed!

**Comment by satoon101** [comment]
Correct me if I am wrong, but I don't think we create a file each day.  I am pretty sure that we create the file at server start using the current day in the file name and continue using that same file no matter which day it is until the server is restarted.

**Comment by invincibleqc** [comment]
Hmm, good point. If the server is not restarted/SP reloaded daily it should continue with the same file making sense to keep the date logged.

**Comment by Ayuto** [comment]
Unless we change this behavior as well.

**Comment by invincibleqc** [comment]
I could certainly see the benefit for servers that stay up for a long period of time.

**Comment by invincibleqc** [comment]
Also quite easy to implement, using [logging.handlers.TimedRotatingFileHandler](https://docs.python.org/3.6/library/logging.handlers.html#logging.handlers.TimedRotatingFileHandler). For example, replacing [line 377](https://github.com/Source-Python-Dev-Team/Source.Python/blob/issue_211/addons/source-python/packages/source-python/loggers.py#L377) with the following:
```python
            self._handler = TimedRotatingFileHandler(log_path, 'D', 1, 7)
```
Would automatically rotate to a new file every single day keeping up to a week of logging (oldest files are deleted when rotating to a new one).

**Comment by Ayuto** [comment]
In an older project I have implemented my own file handler to adress this issue with the file extension:
```python
class RotatingFileHandler(logging.FileHandler):

    """A file handler that writes everything to a day specific file."""

    def __init__(self, filename, mode='a', encoding=None, delay=0,
            strftime='%Y-%m-%d', file_ending='log'):
        self.strftime = strftime
        self.file_ending = file_ending
        super(RotatingFileHandler, self).__init__(
            filename, mode, encoding, delay)

    def _open(self):
        old_filename = self.baseFilename
        self.baseFilename = '%s_%s.%s'% (
            self.baseFilename, time.strftime(self.strftime), self.file_ending)
        stream = super(RotatingFileHandler, self)._open()
        self.baseFilename = old_filename
        return stream

    def emit(self, record):
        self.stream = None
        super(RotatingFileHandler, self).emit(record)
```

**Comment by invincibleqc** [comment]
Yeah I'm not sure I like this implementation and would rather use the class shipped with the package. Otherwise we ends up with the same lazy save/restore workaround on the file name. Also, while I'm not too fan of the file extension, it allows the cleanup of the old files which I think is a great feature because who cares of last week or last month logs?

**Comment by Ayuto** [comment]
I just saw your edit. If your ``DailyRotatingFileHandler`` is working fine, it would be great if you could add it. Though, you might can also get rid of the use of ``LOG_PATH`` and use the path that is passed to the handler instead.

**Comment by invincibleqc** [comment]
I've been working/brainstorming on updating the `loggers` package completely because it currently offer little to no flexibility. The idea would be to inherit from `Manager`/`Logger` directly and fully give control over filtering and formatting (#208) to all handlers either it is for us internally or for users that might use the API into their plugins. That way we can offer our own handlers (main log, console and SP log files) by default to all managers while also allowing them to add/remove their owns with the possibility to manipulate the records before emitting to the handlers and that via object-oriented wrappers instead of the current dict-in-a-dict implementation.

I have some drafts of code but didn't have time to put all the pieces together as of yet. Once I'm done with that, I will push to a branch so we can all discuss the implementation.
