### ISSUE TITLE
TempEntity performance

### ISSUE THREAD

**Issue by jsza** [Source-Python-Dev-Team/Source.Python#223]
I am upgrading from a very old version of SP (> 1 year) and the new TempEntities class is slower than exposing ITempEntsSystem.

```python
import time

from commands.say import SayCommand
from effects.base import TempEntity
from engines.precache import Model
from mathlib import Vector
from players.entity import Player


@SayCommand('test')
def on_test(command, index, teamonly):
    player = Player(index)
    start = player.origin
    end = player.origin + Vector(0, 0, 128)
    material = Model('materials/sprites/laser.vmt')

    s = time.time()
    # emulate lines for 3 boxes
    for x in range(36):
        TempEntity('BeamPoints', alpha=255, red=255, green=255, blue=255,
                   life_time=1.0, start_width=4, end_width=4, frame_rate=255,
                   model=material, halo=material)
        beam.create()

    print('Loop took: ', time.time() - s)

``` 

`Loop took:  0.01820659637451172`

I've had success with this workaround, maybe we can do this for the other wrapper functions in the `effects` package?

```python
    beam = TempEntity('BeamPoints', alpha=255, red=255, green=255, blue=255,
                      life_time=1.0, start_width=4, end_width=4, frame_rate=255,
                      model=material, halo=material)
    for x in range(36):
        beam.start_point = start
        beam.end_point = end
        beam.create()
```

`0.004525899887084961`

**Comment by jsza** [comment]
Uhm, disregard this. I went to make the changes to `effects.beam` and they were already there! Mistakes were made :stuck_out_tongue:

**Comment by jsza** [comment]
And never mind again. I got confused between `effects.beam` and `effects.box`... I'll have a PR up soon.

**Comment by invincibleqc** [comment]
Yes, always a better idea to create TempEntity/UserMessage instances once (into global scope, when possible) and update values that were not known at load time (such as origins, etc.). I can indeed see how looping dozens of times into the effects helpers was costly. Thank you!

I just checked your PR, seems like you forgot to remove line 269 and 278.

**Comment by jsza** [comment]
Thank you, updated.

**Comment by invincibleqc** [comment]
Merged, thank you! To add more info; the reason why `ITempEntsSystem` was faster in the effect wrappers is because it internally does the same thing as your proposed optimization: update values of a global `CBaseTempEntity` instance. The `TempEntity` class is copying that global instance from the engine on initialization (mainly for its dispatch table) because it allows plugins to have their own instances that doesn't get edited/affected by others. So settings values that are known at load time is definitely the way to go so you avoid having to set them later on and save calls which optimize.
