### ISSUE TITLE
CS:GO: Wrong EntityPreHook/EntityCondition.equals_entity_classname() behavior

### ISSUE THREAD

**Issue by backraw** [Source-Python-Dev-Team/Source.Python#231]
I'm using this test code with CS:GO:
```python
is_hkp2000 = EntityCondition.equals_entity_classname('weapon_hkp2000')
is_usp = EntityCondition.equals_entity_classname('weapon_usp')
is_m4a1 = EntityCondition.equals_entity_classname('weapon_m4a1')
is_galil = EntityCondition.equals_entity_classname('weapon_galil')  # CS:S test case for raising ValueError


@EntityPreHook(is_hkp2000, 'secondary_attack')
@EntityPreHook(is_usp, 'secondary_attack')
@EntityPreHook(is_m4a1, 'secondary_attack')
@EntityPreHook(is_galil, 'secondary_attack')
def on_pre_secondary_fire(stack_data):
    weapon = make_object(Weapon, stack_data[0])

    if weapon.owner is not None and weapon.owner.is_player():
        print(weapon.get_property_bool('m_bSilencerOn'))
```
Basically it should print whether the silencer is on for any of the specified weapons, but it does for ANY weapon besides the knife (printing ```False``` for each weapon which don't have that property). How come?

Shouldn't ```weapon.get_property_bool('m_bSilencerOn')``` raise a ValueError for weapons which don't have that property anyways?

I also tested the code with CS:S and it works as expected - print for weapons which have that property and raise ValueError for weapons which don't have it.

Edit: Output of ```sp info```:
```
sp info

Date          : 2017-12-02 18:38:27.822742
OS            : Linux-4.9.63-1-MANJARO-x86_64-with-glibc2.9
Game          : csgo
SP version    : 620
Server plugins:
   00: Source.Python, (C) 2012-2016, Source.Python Team.
SP plugins:
   00: udm, 1.6, https://forums.sourcepython.com/viewtopic.php?f=7&t=1643
```

Edit 2: With CS:S it also only 'fires' only for the specified weapons.

**Comment by KirillMysnik** [comment]
As for "wrong EntityCondition behavior": it's not wrong. It's just that the weapons that you provide don't have their own implementation for `secondary_attack` function. That means that the function is inherited by these weapons from some more generic class - maybe `CBaseCombatWeapon`, I don't know.
And since the hook is set on that implementation, you will have your hook called for any weapons that don't override it.

Take a look at [the snippet in this post](https://forums.sourcepython.com/viewtopic.php?p=9065#p9065) and further replies.
And also take a look at [this recent post](https://forums.sourcepython.com/viewtopic.php?p=11082#p11082) - there are many things in it, but I'm talking about number 4 that elaborates on the role of `EntityCondition` filters.

As for `m_bSilencerOn` - maybe all weapons have that property in CS:GO, not just USP-S and M4A1?

**Comment by satoon101** [comment]
> As for `m_bSilencerOn` - maybe all weapons have that property in CS:GO, not just USP-S and M4A1?

That looks to be correct.  This link is probably a bit outdated, but it does show that `m_bSilencerOn` is a member of `CWeaponCSBase`:
https://pastebin.com/Yk8EvLyv

Whereas, for CS:S, it is only a member of `CWeaponM4A1` and `CWeaponUSP`:
https://pastebin.com/nY7bLxZa

**Comment by backraw** [comment]
That definitely clears things up, thanks! I'll close this issue.
