### ISSUE TITLE
[TF2] player_disconnect event yields no arguments

### ISSUE THREAD

**Issue by ns-phennessy** [Source-Python-Dev-Team/Source.Python#256]
```@Event("player_disconnect")
def log_player_disconnect(event):
    args = event.variables.as_dict()
    print(args)
```
Docs say it should return a bunch of useful information about the client: http://wiki.sourcepython.com/developing/events/tf.html#player-disconnect

Not sure if this is a bug in SP or something quirky the source engine is doing. 

Slightly unrelated; i've noticed there are a handful of events that aren't firing when they should; like "player_shoot". Should I make another for that? Or is that again a source engine being weird thing?

**Comment by invincibleqc** [comment]
> Docs say it should return a bunch of useful information about the client: http://wiki.sourcepython.com/developing/events/tf.html#player-disconnect

I just tested and the following:
```python
from events import Event

@Event('player_disconnect')
def log_player_disconnect(event):
    args = event.variables.as_dict()
    print(args)
```
Works just fine on my side:
```
{'userid': 2, 'reason': 'Disconnect by user.', 'name': "L'In20Cible", 'networkid': '[U:1:19510774]', 'bot': 0}
Dropped L'In20Cible from server (Disconnect by user.)
Server is hibernating
```
Are you sure your function is properly decorated?

> Slightly unrelated; i've noticed there are a handful of events that aren't firing when they should; like "player_shoot". Should I make another for that? Or is that again a source engine being weird thing?

Like I said on the forums, even if an event is declared in the res files it doesn't means they are fired for that specific game. The events that are most likely to be fired for a game are the ones declared into the `../tf/resource/modevents.res` file because these have been declared specifically for that game.

Here it is for TF2: https://pastebin.com/1ZP1yavV (extracted from `../tf/tf2_misc_dir.vpk`)

As you can see, the `player_shoot` event is not declared into that file but is in fact inherited from the engine branch and declared in the `../hl2/resource/gameevents.res` file.

Here it is for TF2: https://pastebin.com/b0YuAk5y (extracted from `../hl2/hl2_misc_dir.vpk`)

The events that are inherited from the engine are unlikely to be fired even if some of them are; which is why they are all documented on the wiki because they are declared from the files that have been parsed to generate the pages. `player_shoot` is not fired on CS game as well; they use `weapon_fire`, etc. You can use the client command `net_showevents` to show the events that are fired and networked in particular situations during the game-play.

**Comment by ns-phennessy** [comment]
Ah yes; I had a typo in my code, apologies

Thanks for the info about event as well; that is very helpful!
