### ISSUE TITLE
EntityPostHook - start_touch crashes on rotating objects.

### ISSUE THREAD

**Issue by Velocity-plus** [Source-Python-Dev-Team/Source.Python#262]
Server crashes when a grenade touches a rotating object, in this case, a **disco light bulb** in the map trikz_advanced_csgo. The crash doesn't happen on a specific line, it happens as long as the PostHook is initialized.

Tested on both Linux and Windows
Game: CSGO

I think this is also mentioned here: https://forums.sourcepython.com/viewtopic.php?f=20&t=1447&p=9615&hilit=memory+make+object+crash#p9615 all tho, I'm using a PostHook.
Regarding this forum post, what does entity condition do, if it doesn't filter out anything?

```python
@EntityPostHook(EntityCondition.is_player, 'start_touch')
def start_touch_func(args, ret):
    base_entity0 = make_object(BaseEntity, args[0])
    base_entity1 = make_object(BaseEntity, args[1])

    if not base_entity0.is_player() or not base_entity1.is_player():
        return

```
I get the following error in the console before it crashes:
`WARNING: Watchdog timer exceeded, aborting! ERROR`

EDIT:
If it is a PreHook instead of a PostHook, do I need to return DataType.VOID ? What does this do exactly?

**Comment by jordanbriere** [comment]
Closing this as I believe this was fixed into https://github.com/Source-Python-Dev-Team/Source.Python/commit/74c2b0189c4b0620a4e7be2680d73af509fbc249. If you still have issues, please re-open with more information (complete code including imports, map name, coordinates, etc.).

>Regarding this forum post, what does entity condition do, if it doesn't filter out anything?

The test function you can pass to the hook decorators are used to let you control from which class the function should be retrieved. This is useful when registering a hook on function that are virtual, otherwise the first entity matching would register the hook and it can be on an override that won't get called for other classes or behave differently than what you want. For example, you try to hook `Player.some_method` which wraps `CCSPlayer::SomeMethod`. Now, if the first entity matching is an human player, then the hook will be correctly installed. But now suppose the first entity matching is a bot, and that this method was virtual and that the `CCSBot` implement its own your hook will be installed on `CCSBot::SomeMethod` instead. To ensure the hook is registered on an human, you pass a test function to the hook decorator:

```
@PreHook(EntityCondition.is_human_player, 'some_method')
def...
```

Now you are sure your hook will always be registered on `CCSPlayer::SomeMethod`. The `EntityCondition` class is really just a namespace that provides some commonly used test functions.

A good example of this the [weapons.restrictions](https://github.com/Source-Python-Dev-Team/Source.Python/blob/972547be070e74a3f785284cefef53d98fab83c8/addons/source-python/packages/source-python/weapons/restrictions.py#L384-L385) module, where the hook wouldn't be called for bots if registered on an human and vice versa so to ensure it is called for everyone, the callback is registering both; human and bot methods.

As for filtering the callbacks to match that condition, I remember we internally discussed that possibility in the past but not sure if/when we will get back to that topic.
