### ISSUE TITLE
Raising an exception with %s crashes the server

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#275]
Put this in an SP plugin and load the plugin. The server will crash during printing the exception.
```python
def crash():
    name = 'asd'
    raise NameError("'%s' crash :( ... f-strings and format() work fine."% name)
    
crash()
```
This also happens if you replace the entire ``source-python/__init__.py`` with this snippet. Python issue? Reproduced with CS:S on Windows and Linux.

**Comment by invincibleqc** [comment]
The crash occurs when the line itself is printed to the console. The issue appears to be [console_message](https://github.com/Source-Python-Dev-Team/Source.Python/blob/ae51b4cf443f91880bcce658b58a159c9771647c/src/core/modules/core/core.cpp#L34-L44) passing the text to `ConMsg` which expects arguments to format the `%s` values. But since nothing is passed, it reads random addresses from an empty va_list when [the output is formatted](https://github.com/alliedmodders/hl2sdk/blob/46713a22a02a349659e60ed82b15869b1da94d2f/public/tier0/platform.h#L557) and forwarded to printf. This crashes:
```python
from _core import console_message
console_message(""""'%s' crash :( ... f-strings and format() work fine."% name""")
```
We need to find and escape all the `%` to `%%` to tell the engine we don't want any formatting on them so that we pass the following instead:
```python
from _core import console_message
console_message(""""'%%s' crash :( ... f-strings and format() work fine."%% name""")
```

**Comment by Ayuto** [comment]
Hmm, I think there are better ways to fix this issue like using a function that really just prints the message instead of doing formatting stuff.

This solution can also still run into the same problem if it's getting chunked. Moreover, it doesn't take care about properly escaped percent signs.

**Comment by invincibleqc** [comment]
> Hmm, I think there are better ways to fix this issue like using a function that really just prints the message instead of doing formatting stuff.

Yes, my original idea was to simply use `cout` or something but then we no longer have our fallback for issue #175 because we operate outside of the engine's hook. The engine doesn't provides any wrapper that doesn't use formatting. I would be fine with it, as long as it only affects listen servers but there is no guarantee that it won't also affects certain features for dedicated servers as well (for example, the `OnServerOutput` listener might not be able to catches these messages, etc.). Perhaps we could directly write to the `CONOUT$` channel, but then it only works for dedicated servers. I believe the safest approach is to escape the formatting.

> This solution can also still run into the same problem if it's getting chunked. Moreover, it doesn't take care about properly escaped percent signs.

Good point! The replacements should be done in the loop instead.

**Comment by invincibleqc** [comment]
Well... the solution was actually so obvious and simple. :laughing:

**Comment by Ayuto** [comment]
That's a good one :D

**Comment by Ayuto** [comment]
For reference:
https://github.com/Source-Python-Dev-Team/Source.Python/commit/cf91d9c8fc56f48da2a0be33e47b6a7363fa2e85
https://github.com/Source-Python-Dev-Team/Source.Python/commit/58fa670ab495a5c4e9d52d78d727294b90bbc25f
