### ISSUE TITLE
[CSGO] Server crashes on load

### ISSUE THREAD

**Issue by ggEasyz** [Source-Python-Dev-Team/Source.Python#283]
Windows 10 1903
SP version - 691
Server crash on Source.Python loading. Clean server, Metamod/Sourcemod not installed.
> Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
No web api auth key specified - workshop downloads will be disabled.
[Source.Python] Loading...

**Comment by jordanbriere** [comment]
Thanks for the report! Seems like Source.Python needs to be recompiled for CS:GO, along with our `tier1.lib` patch due to recent changes to the `ICvar::RegisterConCommand` method. Until an official build is made available, you can download and replace the following [../addons/source-python/bin/core.dll](https://drive.google.com/open?id=1e51HVmcArhfNLzhOr9Q3MWk_3yvCksU-) file for your server.

**Comment by Ayuto** [comment]
I just created a new build. Please test again to see if it's working now.
