### ISSUE TITLE
css armor issue

### ISSUE THREAD

**Issue by srpg** [Source-Python-Dev-Team/Source.Python#301]
In my rpg plugin got error on armor. 

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\events\listener.py", line 92, in fire_game_event
    callback(game_event)
  File "..\addons\source-python\plugins\rpg\skills\armor.py", line 34, in rpg_skillupgrade
    rpglib.setArmor(userid, rpglib.getArmor(userid) + SKILL_ARMOR_ADD)

TypeError: must be str, not int
```

 in rpglib those armor stuff is

```
def getArmor(userid):
    return Player(index_from_userid(userid)).get_property_char('m_ArmorValue')

def setArmor(userid, value):
    try:
        Player(index_from_userid(userid)).set_property_char('m_ArmorValue', str(value))
```

**Comment by invisiblesoldiers** [comment]
m_ArmorValue is type of int, not char, 
```rpglib.setArmor(userid, rpglib.getArmor(userid) + SKILL_ARMOR_ADD)```
_TypeError: must be str, not int_, because _SKILL_ARMOR_ADD_ is **int**, and _getArmor_ returns char
str + int = TypeError
Try to use functions: _get_property_int, set_property_int_

**Comment by invisiblesoldiers** [comment]
Also there are already the armor property:
http://wiki.sourcepython.com/developing/modules/players._base.html?highlight=armor#_players.PlayerMixin.armor

**Comment by srpg** [comment]
in console says TypeError: Property "m_ArmorValue" is of type char not int

**Comment by invisiblesoldiers** [comment]
> in console says TypeError: Property "m_ArmorValue" is of type char not int
Hmm, probably, m_ArmorValue is network property and you should use _get_network_property_*_ player.get_network_property_int('m_ArmorValue') works great.

**Comment by jordanbriere** [comment]
As @invisiblesoldiers suggested, you should rather use the `Player.armor` property which will takes care of translating the char from-to an integer for you (because `PlayerMixin::GetArmor` returns an `int`, so the compiler knows what to do with that `char`). Otherwise, if you absolutely want to query the property yourself, then you must cast from-to char using the [chr](https://docs.python.org/3.6/library/functions.html#chr) and [ord](https://docs.python.org/3.6/library/functions.html#ord) built-ins. For example, increase the current player's armor by 1:

```
pl.set_property_char('m_ArmorValue', chr(ord(pl.get_property_char('m_ArmorValue')) + 1))
```

Though, I would not recommend that. Not only this makes your code fails on HL2:DM, but also make it much slower with the current version. There is no reason not to use the `Player.armor` wrapper.
