### ISSUE TITLE
Entity Outputs are Disabled

### ISSUE THREAD

**Issue by msmaiaa** [Source-Python-Dev-Team/Source.Python#306]
![image](https://user-images.githubusercontent.com/30882102/75601427-c3d16e80-5a99-11ea-9739-7863c5adfc51.png)
So, i cant use any kz plugins (i tried GOKZ and kztimer) with sourcepython because it gives me this error, i tried removing source.python and it works fine, please fix :(

**Comment by jordanbriere** [comment]
The problem is that SourceMod do not check for hooked signatures, so if the original one was already detoured by Source.Python then it will fails. However, Source.Python will fallback to search for them, so if you delete the `../addons/source-python.vdf` file and add `plugin_load addons/source-python` to your `autoexec.cfg` file then everything should work properly. This would ensure Source.Python be loaded after SourceMod allowing it to hook the signature for that method first.

**Comment by msmaiaa** [comment]
Thank you, you saved my life and made my day :)
