### ISSUE TITLE
Missing weapons data cause NotImplementedError on Weapon instantiation.

### ISSUE THREAD

**Issue by Sam839** [Source-Python-Dev-Team/Source.Python#308]
```[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\plugins\VoiceMod\VoiceMod.py", line 117, in PreEmitSound
    weapon = client.get_active_weapon()
  File "..\addons\source-python\packages\source-python\players\_base.py", line 803, in get_active_weapon
    return Weapon(index)
  File "..\addons\source-python\packages\source-python\entities\_base.py", line 127, in __call__
    obj = super().__call__(index)
  File "..\addons\source-python\packages\source-python\weapons\_base.py", line 40, in __init__
    WeaponMixin.__init__(self, index)
  File "..\addons\source-python\packages\source-python\weapons\default.py", line 29, in __getattribute__
    'No support for game "{0}"'.format(GAME_NAME))

NotImplementedError: No support for game "tf"
```
```
--------------------------------------------------------
Checksum      : beee61bc2b45f1329ec887af411ae5b3
Date          : 2020-03-17 17:14:32.592269
OS            : Windows-10-10.0.18362
Game          : tf2
SP version    : 695
Github commit : 92b3adfaaaf1bb9ecd2be1ddad55bc68589b4152
Server plugins:
   01: Source.Python, (C) 2012-2019, Source.Python Team.
SP plugins:
   00: BadSetLocalAnglesFixer
   01: AdvancedBunnyHop
   02: AntiAutoKick
   03: InstantReSpawn
   04: UTF8
   05: TauntMusicChanger
   06: VoiceMod
--------------------------------------------------------
```
The problem started after the last update.

**Comment by invisiblesoldiers** [comment]
You can use it for now
```python
weapon = baseentity_from_inthandle(self.active_weapon_handle)

**Comment by Sam839** [comment]
```
weapon = Entity(index_from_inthandle(client.active_weapon_handle))
weapon.call_input('Color', Color(255,0,0))
```
This is the best solution for this task. Why did suddenly support for tf2 stop?

**Comment by jordanbriere** [comment]
This error happens when the `weapons.manager.weapon_manager` singleton is set to a `NoWeaponManager` instance which is defined [here](https://github.com/Source-Python-Dev-Team/Source.Python/blob/972547be070e74a3f785284cefef53d98fab83c8/addons/source-python/packages/source-python/weapons/manager.py#L170-L181) when the specific weapon file for that game is not found.

TF2 never had any data, as you can see in the [data directory](https://github.com/Source-Python-Dev-Team/Source.Python/tree/master/addons/source-python/data/source-python/weapons), but we made a recent change into #298 to validate the weapons using the manager so that error is now thrown on all games that don't have any data whenever a `Weapon` instance is created.

This is a regression and I'm not sure what is the best play here; finally add weapons support to all games, or revert to using hard-coded classes for weapon validation. The former would be the best, and we could certainly use your guys help to build and validate the data for the games you are playing.

That said, an easy workaround for now without editing your codes or Source.Python would be to make a separate plugin with the following code:

```python
import weapons.manager

class Manager(object):
    def __contains__(self, class_name):
        return True

weapons.manager.weapon_manager = Manager()
```

And ensure it is being loaded before any other plugins. This would revert to the previous no-check behaviour by always returning `True` for weapon validation. And when a proper fix for this is available you can just uninstall this plugin instead of re-editing all the others.

**Comment by jordanbriere** [comment]
I've added basic data for the games that were not supported. I don't know these games very well so this doesn't add full support for advanced filtering, or specialized features such as ammo, clip, etc. but this should fix this issue.

If anyone have the knowledge and want to add more support please go ahead and submit a PR.

As a side not, Blade doesn't seems to use weapons besides the default cubemap inherited from the engine and seems to use a special sword system. I wasn't able to confirm in-game, because the `IVEngineServer` interface can't be retrieved for some reasons.

Anyways, please add the missing data files to your servers and see if that fixes the issues for you.

Thanks!

**Comment by Sam839** [comment]
Since my server is unavailable by remote connection for a month. I will accept this information
