### ISSUE TITLE
Data: buymenu index

### ISSUE THREAD

**Issue by timo-reichl** [Source-Python-Dev-Team/Source.Python#328]
I'm missing the buymenu indeces (for CS:GO at least). I need that because:

```python
@ClientCommandFilter
def client_command_filter(command, index):
    player = PlayerEntity(index)
    client_command = command[0]

    if client_command == 'buy':
        print("buy:", command.arg_string)
```
prints `buy: unused 6` for the deagle, for example. The index seems to be baked into the engine code, so I think that's somewhat stable. I don't know about the `unused`, tho. That prints for any weapon I buy. But for the index, I'm 100% sure it's mapped to the weapon you want to buy.

Can we add that to the data files like so?
```ini
[[deagle]]
    slot = 1
    maxammo = 35
    ammoprop = 1
    clip = 7
    cost = 700
    item_definition_index = 1
    buyindex = 6
    tags = "all,secondary,pistol"
```

Can't think of something better than `buyindex` right now. I can create a pull request if that seems to be a good idea for you. I'll need map those indeces for a plugin anyway.

**Comment by timo-reichl** [comment]
I just realized that can't really work, because the AK47 and the M4A4 share the same index, for example. Maybe that sort of thing can't really be implemented like this.

**Comment by jordanbriere** [comment]
@timo-reichl Couldn't you use a hook on `buy_internal` instead? For example:

https://github.com/Source-Python-Dev-Team/Source.Python/blob/f2c2eedb65ccf642505509bba6cc44087edd6760/addons/source-python/packages/source-python/weapons/restrictions.py#L394-L407

I'm not sure we should maintain these indexes, because I have no idea if they are unlikely to changes or not. We don't even support `weapons.scripts` for that game because they were changing every other weeks.

**Comment by timo-reichl** [comment]
To be honest I have no idea what I was trying to achieve here since the issue is 2 years old and things have probably changed so much the question doesn't even apply anymore :D

Maybe the hook didn't work correctly back then with the version of the game engine (you know Valve and engine updates...).

Anyhow I'll close the issue - thanks tho!
