### ISSUE TITLE
TempEntity bug

### ISSUE THREAD

**Issue by invisiblesoldiers** [Source-Python-Dev-Team/Source.Python#333]
I created temp entity through effects.base.TempEntity once and then reuse the entity multiply times to send it clients again. But when map was changed and I use again the entity, mystical things happen, when you send it again the game may crash or effects don't render at all, or change color and width on a client.
Does it source engine bug or source.python?

**Comment by jordanbriere** [comment]
Your temp entity contains outdated indexes.

**Comment by Ayuto** [comment]
@invisiblesoldiers Is this still a problem? If yes, could you please add your test code and the output of ``sp info``?

**Comment by vinci6k** [comment]
Ran into the same problem, just make sure you [reinitialize the TempEntity](https://github.com/vinci6k/curving-flash/blob/master/helpers/trails.py#L21) on map load.

**Comment by jordanbriere** [comment]
> 
> 
> Ran into the same problem, just make sure you [reinitialize the TempEntity](https://github.com/vinci6k/curving-flash/blob/master/helpers/trails.py#L21) on map load.

Yes, the issue is that the model indexes changes on new map because the string tables are re-initialized. Actually, I believe the models should be reset every times the effect is sent. The reason for this is that if the user data of that string changes in the string table, it will potentially have the same result (client crash). Not that it should happens though, but always a possibility.
