### ISSUE TITLE
Expose CSteamID

### ISSUE THREAD

**Issue by necavi** [Source-Python-Dev-Team/Source.Python#45]
Any chance that CSteamID (returned by engine_server.get_client_steamid(edict) could be exposed? I'd like to use it to generate Steam3/SteamID64 (community/Account ID) tokens in a more future-proof manner than blindly transforming the client's authstring. Ex. https://github.com/alliedmodders/sourcemod/blob/ff27484527344ec3c5d591bd9610e07f00ff31de/core/PlayerManager.cpp#L1992-L2098

**Comment by satoon101** [comment]
We can expose that, but we already do some of the work shown in that SM function within [players.helpers.uniqueid_from_playerinfo](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/players/helpers.py#L138).  I would suggest we continue to do the work within that function itself instead of internally, but it could definitely help to have the CSteamID instance instead of a string.

**Comment by Ayuto** [comment]
Just exposed the basic stuff for CSteamID. Obviously, there is more we can expose, which is why I have created a complete new module.
