### ISSUE TITLE
Different behavior for checks that the player is dead in "dod"

### ISSUE THREAD

**Issue by dronelektron** [Source-Python-Dev-Team/Source.Python#476]
Given the following code:

```Python
from commands import CommandReturn
from commands.client import ClientCommand
from players import PlayerInfo
from players.entity import Player


@ClientCommand('sp_is_dead')
def is_player_dead(command, index):
    player = Player(index)
    is_dead_1 = player.dead
    is_dead_2 = PlayerInfo.is_dead(player.playerinfo)

    print(f'[DEBUG] Is dead 1 - {is_dead_1}')
    print(f'[DEBUG] Is dead 2 - {is_dead_2}')

    return CommandReturn.BLOCK
```

Case 1 (Bug?):
1. I'm alive
2. Called "sp_is_dead"
3. Result: is_dead_1 = False, is_dead_2 = False
4. Killed myself with grenade
5. Called "sp_is_dead"
6. Result: is_dead_1 = True, is_dead_2 = False (expected to be True)

Case 2 (OK):
1. Joined Spectator team
2. Called "sp_is_dead"
3. Result: is_dead_1 = True, is_dead_2 = True

**Comment by CookStar** [comment]
Player.dead returns True when Player.life_state([m_lifeState](https://github.com/alliedmodders/hl2sdk/blob/78dab58646d5983c77af44c45a877b89196eb82c/public/const.h#L273)) is not LIFE_ALIVE(0), but [CBasePlayer::IsDead()](https://github.com/alliedmodders/hl2sdk/blob/78dab58646d5983c77af44c45a877b89196eb82c/game/server/player.cpp#LL1567C19-L1567C25]) and [CPlayerInfo::IsDead()](https://github.com/alliedmodders/hl2sdk/blob/78dab58646d5983c77af44c45a877b89196eb82c/game/server/player.cpp#LL9075C1-L9075C6) return True only when m_lifeState is LIFE_DEAD(2).

In the above code, PlayerInfo.is_dead returns False because Player.life_state is LIFE_DYING(1), meaning that the player is not yet completely dead. It should return True when the death animation is finished.

**Comment by dronelektron** [comment]
Oh, thanks for the explanation, I tested it and it works just like you said
