### ISSUE TITLE
Add dump_datamaps to core/dumps.py

### ISSUE THREAD

**Issue by Ayuto** [Source-Python-Dev-Team/Source.Python#57]
The function should require a datamap_t argument. This should be used to dump the datamap and all of its base maps.

**Comment by invincibleqc** [comment]
I don't agree on "should require a datamap_t argument". Mainly cause those are dump functions used by "sp dump" and should only requires strings arguments. I think the function itself should rather accept a file name then an optional class name:

sp dump datamaps <file name> [class name]

If class name is not specified, loop through the factories and dump everything otherwise only create the specified entity, dump it then delete it.

**Comment by Ayuto** [comment]
Yes, as for the console command it makes sense to have a function that doesn't require that argument. But there are also classes, which have datamaps, but aren't entities. So, it would probably be the best to have both. "sp dump datamaps "file name" [class name]" can create the entity/entities and pass the datamap(s) to the function that requires the datamap argument.

**Comment by invincibleqc** [comment]
I guess we could always inject a "dump" method to the DataMap class which only accept a file name.
