### ISSUE TITLE
mathlib's Vector long float issue

### ISSUE THREAD

**Issue by high-voltage** [Source-Python-Dev-Team/Source.Python#66]
I came across an issue where I precalculate long floats, and after initializing a Vector object, the x y z values differed from the original ones.
It looks like after the 9th number, mathlib.Vector() has a calculation error.

Example:

```
from mathlib import Vector

x, y, z = (-14.49353846153846, -10.87015384615385, 0.31507692307692)
vec = Vector(x, y, z)

print(x, y, z)
print(vec.x, vec.y, vec.z)
```

Result is this (on every 9th number it starts to differ):
-14.49353846153846,   -10.87015384615385,   0.31507692307692
-14.493538856506348, -10.870153427124023, 0.31507691740989685

**Comment by Ayuto** [comment]
The problem is that Vector is using the "float" data type to store these three values, but that data type is only 4 bytes big. Therefore, it isn't able to store values with that precision.

Take a look at this example.
```
import memory

x = -14.493538861538464
print(x) # Will print -14.493538861538464

# Store the value using a float (4 bytes)
ptr = memory.alloc(4)
ptr.set_float(x)
print(ptr.get_float()) # Will print -14.493538856506348

# Store the value using a double (8 bytes)
ptr = memory.alloc(8)
ptr.set_double(x)
print(ptr.get_double()) # Will print -14.493538861538464
```
In this case the precision is lost if you use a float.

You can find more information about that on Google.
